version: '3.7'
services:
  postgres:
    restart: always
    image:
      postgres:11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  flaskapp:
    build: .
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - .:/app
